### ISSUE TITLE
[Help Request] Second Scenario Is Freezing On Test Starting

### ISSUE THREAD

**Issue by yahyakara** [vrnvorona/sample_app#1]
Hi,
Thanks for your project It is so helpful. I implement our project with your setup :). First scenario is running perfectly  but 
When second scenario started test freezing on Test starting screen.

Regards

**Comment by vrnvorona** [comment]
Hi
There should be errors in console output. Usually tests hang because of some exceptions
I would be able to check it myself in January, but I remember both scenarios working
